### ISSUE TITLE
Fastlane: full description has broken HTML tag (not properly closed)

### ISSUE THREAD

**Issue by IzzySoft** [odrevet/bide_et_musique_flutter#7]
`fastlane/metadata/android/en-US/full_description.txt` is partly broken: the `<b>` tag on the first line is not properly closed. Can you please fix that? Thanks!

**Comment by odrevet** [comment]
thank for reporting this. i fixed it and made a new release

**Comment by IzzySoft** [comment]
Wow, that was fast – thanks a lot! Should be picked up by F-Droid within a week (with the next build cycle that is).
